[workspace]
authors = ["小猫 <i@sinofine.me>"]
channels = ["conda-forge"]
name = "pokemon"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.12,<3.13"
sage = ">=10.7,<11"
